### ISSUE TITLE
List All Todo Page

### ISSUE THREAD

**Issue by ShuaibShaban** [ShuaibShaban/TaskRail#6]
A list all todos page should be the one in default when a user logs in successfully in my application.
The page should be having the following:

- [ ] A create ne todo button
- [ ] A list of all todos each on it's card
- [ ] All the available todos should be having an edit icon and a trash can icon.
